version: '3.5'

services:
  api-app:
    build: ./server
    networks:
      - app-dev
    container_name: api-app
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8182:8888

  ui-app:
    build: ./UI
    networks:
      - app-dev
    container_name: ui-app
    volumes:
      - ./ui:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - api-app

networks:
  app:
  service-webproxy:
    external: true