version: '3.5'

services:
  api-app:
    build: ./server
    networks:
      - app-dev
    container_name: api-app
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8888:8888

  ui-app:
    build: ./client
    networks:
      - app-dev
    container_name: ui-app
    volumes:
      - ./client:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - api-app

networks:
  app-dev:
  service-webproxy:
    external: true
